version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ports:
      - "5000:5000"
    environment:
      - DEBUG=True
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mysql_exercise_db
      - MYSQL_USER=mysql_practice
      - MYSQL_PASSWORD=practice_pass_2024
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ../database/privileges.sql:/docker-entrypoint-initdb.d/privileges.sql

volumes:
  mysql_data: 